print("My name is {}.I am {} years old".format('Sounak',18))
print("Here I am testing git and github for the first time")
print("Github account opened - {}/{}/{}".format(29,'09',2023))
print("First code on git - {}/{}/{}".format(29+1,'09',23))
print("First programming language learned - C (on May 2021)")
print("Second language learned - C++ (on Sept 2021)")
print("Python learned - {} {},{}".format(27,'June',2023))
print("First python library learned and mastered - {}".format('NumPy'))
print("These are the milestones of computing I've reached so far.",end="")
print(" Will soon update new information here ")
print("Till then, Happy Coding !!:)")